-- Database Schema Export for data/ai_insight.db
-- Generated by export_schema.py

-- Table: dashboard_widgets
CREATE TABLE dashboard_widgets (
	dashboard_id INTEGER NOT NULL, 
	widget_id INTEGER NOT NULL, 
	layout JSON, 
	PRIMARY KEY (dashboard_id, widget_id), 
	FOREIGN KEY(dashboard_id) REFERENCES dashboards (id), 
	FOREIGN KEY(widget_id) REFERENCES widgets (id)
);

-- Indices for dashboard_widgets

--------------------------------------------------

-- Table: dashboards
CREATE TABLE "dashboards" (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR,
                description VARCHAR,
                createdAt BIGINT,
                updatedAt BIGINT
            );

-- Indices for dashboards
CREATE INDEX ix_dashboards_id ON dashboards (id);
CREATE INDEX ix_dashboards_name ON dashboards (name);

--------------------------------------------------

-- Table: data_sources
CREATE TABLE data_sources (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR,
            description VARCHAR,
            config JSON
        );

-- Indices for data_sources
CREATE INDEX ix_data_sources_id ON data_sources (id);
CREATE INDEX ix_data_sources_name ON data_sources (name);

--------------------------------------------------

-- Table: datasets
CREATE TABLE datasets (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR, description VARCHAR, sql VARCHAR, previewData JSON, createdAt BIGINT, dataSourceId INTEGER);

-- Indices for datasets
CREATE INDEX ix_datasets_id ON datasets (id);
CREATE INDEX ix_datasets_name ON datasets (name);

--------------------------------------------------

-- Table: tables
CREATE TABLE tables (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR,
            description VARCHAR,
            columns JSON,
            rows JSON,
            "dataSourceId" INTEGER, simple_description TEXT,
            FOREIGN KEY("dataSourceId") REFERENCES "data_sources" (id)
        );

-- Indices for tables
CREATE INDEX "ix_tables_dataSourceId" ON tables ("dataSourceId");
CREATE INDEX ix_tables_id ON tables (id);
CREATE INDEX ix_tables_name ON tables (name);

--------------------------------------------------

-- Table: templates
CREATE TABLE templates (
	id INTEGER NOT NULL, 
	name VARCHAR, 
	description VARCHAR, 
	type VARCHAR, 
	category VARCHAR, 
	content VARCHAR, 
	config JSON, 
	icon VARCHAR, 
	"createdAt" BIGINT, 
	"updatedAt" BIGINT, 
	PRIMARY KEY (id)
);

-- Indices for templates
CREATE INDEX ix_templates_id ON templates (id);
CREATE INDEX ix_templates_name ON templates (name);

--------------------------------------------------

-- Table: widgets
CREATE TABLE "widgets" (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                datasetId INTEGER,
                name VARCHAR,
                description VARCHAR,
                config JSON,
                type VARCHAR DEFAULT 'widget',
                content VARCHAR,
                createdAt BIGINT,
                updatedAt BIGINT
            );

-- Indices for widgets

--------------------------------------------------

