-- Database Schema Export for data/ai_insight.db
-- Generated by export_schema.py

-- Table: chart_templates
CREATE TABLE chart_templates (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR,
            description VARCHAR,
            "isCustom" BOOLEAN,
            type VARCHAR,
            icon VARCHAR,
            "customSpec" JSON,
            "chartParams" JSON
        );

-- Indices for chart_templates
CREATE INDEX ix_chart_templates_id ON chart_templates (id);

--------------------------------------------------

-- Table: dashboard_widgets
CREATE TABLE dashboard_widgets (
	dashboard_id INTEGER NOT NULL, 
	widget_id INTEGER NOT NULL, 
	layout JSON, 
	PRIMARY KEY (dashboard_id, widget_id), 
	FOREIGN KEY(dashboard_id) REFERENCES dashboards (id), 
	FOREIGN KEY(widget_id) REFERENCES widgets (id)
);

-- Indices for dashboard_widgets

--------------------------------------------------

-- Table: dashboards
CREATE TABLE "dashboards" (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR,
                description VARCHAR,
                createdAt BIGINT,
                updatedAt BIGINT
            );

-- Indices for dashboards
CREATE INDEX ix_dashboards_id ON dashboards (id);
CREATE INDEX ix_dashboards_name ON dashboards (name);

--------------------------------------------------

-- Table: data_sources
CREATE TABLE data_sources (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR,
            description VARCHAR,
            config JSON
        );

-- Indices for data_sources
CREATE INDEX ix_data_sources_id ON data_sources (id);
CREATE INDEX ix_data_sources_name ON data_sources (name);

--------------------------------------------------

-- Table: datasets
CREATE TABLE datasets (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR, description VARCHAR, sql VARCHAR, previewData JSON, createdAt BIGINT, dataSourceId INTEGER);

-- Indices for datasets
CREATE INDEX ix_datasets_id ON datasets (id);
CREATE INDEX ix_datasets_name ON datasets (name);

--------------------------------------------------

-- Table: tables
CREATE TABLE tables (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR,
            description VARCHAR,
            columns JSON,
            rows JSON,
            "dataSourceId" INTEGER,
            FOREIGN KEY("dataSourceId") REFERENCES "data_sources" (id)
        );

-- Indices for tables
CREATE INDEX "ix_tables_dataSourceId" ON tables ("dataSourceId");
CREATE INDEX ix_tables_id ON tables (id);
CREATE INDEX ix_tables_name ON tables (name);

--------------------------------------------------

-- Table: web_components
CREATE TABLE web_components (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name VARCHAR,
            description VARCHAR,
            code VARCHAR,
            "createdAt" BIGINT
        );

-- Indices for web_components
CREATE INDEX ix_web_components_id ON web_components (id);

--------------------------------------------------

-- Table: widgets
CREATE TABLE "widgets" (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                datasetId INTEGER,
                name VARCHAR,
                description VARCHAR,
                config JSON,
                timestamp BIGINT
            );

-- Indices for widgets
CREATE INDEX ix_widgets_id ON widgets (id);

--------------------------------------------------

