import sqlite3
import os

# Define database path
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, 'data', 'ai_insight.db')
OUTPUT_FILE = os.path.join(BASE_DIR, 'database_schema.sql')

def export_schema():
    if not os.path.exists(DB_PATH):
        print(f"Database not found at {DB_PATH}")
        return

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(f"-- Database Schema Export for data/ai_insight.db\n")
        f.write("-- Generated by export_schema.py\n\n")

        # Get all tables
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';")
        tables = [row[0] for row in cursor.fetchall()]
        tables.sort()

        for table in tables:
            f.write(f"-- Table: {table}\n")
            
            # Get Create Table Statement
            cursor.execute(f"SELECT sql FROM sqlite_master WHERE type='table' AND name=?;", (table,))
            res = cursor.fetchone()
            if res:
                create_stmt = res[0]
                f.write(create_stmt)
                if not create_stmt.strip().endswith(';'):
                    f.write(';')
                f.write("\n")

            # Get Indices
            f.write(f"\n-- Indices for {table}\n")
            cursor.execute(f"SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name=? AND sql IS NOT NULL;", (table,))
            indices = cursor.fetchall()
            for idx in indices:
                stmt = idx[0]
                f.write(stmt)
                if not stmt.strip().endswith(';'):
                    f.write(';')
                f.write("\n")
            
            f.write("\n" + "-"*50 + "\n\n")

    conn.close()
    print(f"Schema exported to {OUTPUT_FILE}")

if __name__ == "__main__":
    export_schema()
