
export interface Column {
  name: string;
  type: 'string' | 'number' | 'date' | 'boolean';
  alias?: string; // New: User-friendly name
  description?: string; // AI Context Annotation
}

export interface DataRow {
  [key: string]: string | number | boolean | null;
}

export interface TableData {
  id: number;
  name: string;
  columns: Column[];
  rows: DataRow[];
  description?: string;
  dataSourceId?: number; // Link table to its source
}

export interface DatabaseConfig {
  type: 'oracle' | 'mysql' | 'postgres';
  name: string; // Connection name (e.g., "Sales DB")
  host: string;
  port: string;
  serviceName: string;
  database?: string;
  username: string;
  password?: string;
}

export interface DataSource {
  id: number;
  name: string;
  description?: string; // AI Context Annotation for the source
  config: DatabaseConfig;
  tables: TableData[];
}

// Definition for a custom chart's visual structure
export interface CustomChartSeries {
  type: 'bar' | 'line' | 'area' | 'scatter';
  dataKeyIndex: number; // Index in the dataKeys array (0, 1, 2...)
  color?: string;
  name?: string; // Label override
  stackId?: string; // For stacked charts
  yAxisId?: 'left' | 'right'; // Dual axis support
}

export interface CustomChartReferenceLine {
  y?: number;
  label?: string;
  color?: string;
}

export interface CustomChartSpec {
  series: CustomChartSeries[];
  referenceLines?: CustomChartReferenceLine[];
  yAxisLeft?: { label?: string; unit?: string };
  yAxisRight?: { label?: string; unit?: string };
}

export interface ChartConfig {
  type: 'bar' | 'line' | 'pie' | 'area' | 'radar' | 'scatter' | 'map' | 'custom' | 'web-component' | 'funnel' | 'gauge' | 'boxplot';
  variant?: string; // 'default', 'stacked', 'horizontal', 'donut', 'step', etc.
  xAxisKey: string;
  dataKeys: string[]; 
  title: string;
  description: string;
  tableName?: string;
  sql?: string; 
  customSpec?: CustomChartSpec; // Only present if type is 'custom'
  chartParams?: any; // Generic bag for extra parameters
  webComponentCode?: string; // Store code for web-component type
  filters?: { column: string }[]; // New: Selected columns for filtering data
  rawData?: any; // New: Raw data override for when AI provides direct data values (e.g. array labels)
  autoUpdate?: { // New: Auto-refresh configuration
    enabled: boolean;
    interval: number; // seconds
  };
}

// Global Template Definition for the Library
export interface ChartTemplate {
  id: number;
  name: string;
  description: string;
  isCustom: boolean;
  type: ChartConfig['type']; // 'bar', 'line', etc. or 'custom'
  icon: string; // Lucide icon name string
  customSpec?: CustomChartSpec; // The template for custom charts
  chartParams?: any; // Generic bag for extra parameters
}

export interface SavedComponent {
  id: number;
  name: string;
  description: string;
  datasetId: number;
  config: ChartConfig;
  createdAt: number;
}

// React Web Component Template generated by AI
export interface WebComponentTemplate {
  id: number | string;
  name: string;
  description: string;
  code: string; // The raw React component code (JSX)
  datasetId?: number; // Optional bound dataset
  createdAt: number;
  dataExample?: string; // Example of the data structure expected by the component
  structuredExample?: {
    table?: {
      headers: string[];
      rows: (string | number)[][];
    };
    json?: any;
    sql?: string;
    description?: string;
  };
}

export interface ChatMessage {
  role: 'user' | 'model';
  content: string;
  chartConfig?: ChartConfig;
  webComponent?: { name: string; code: string }; // Generated web component
  timestamp: number;
  image?: string; 
}

export interface WidgetLayout {
  colSpan: number; // 1 to 12
  height: 'normal' | 'tall' | number; // Support pixel height
  i?: number; // Order index
}

export interface DashboardWidget {
    id: string | number;
    config: ChartConfig;
    datasetId?: number; // Renamed from tableId. Optional because some widgets might not need dataset (e.g. static text)
    tableId?: number; // Legacy support
    timestamp: number;
    layout: WidgetLayout;
}

export interface Dashboard {
  id: number;
  name: string;
  description?: string;
  widgets: DashboardWidget[];
  createdAt: number;
  updatedAt?: number;
}

export interface DatasetBase {
  id: number;
  name: string;
  description?: string;
  dataSourceId: number;
  sql: string;
  previewData?: TableData;
  createdAt: number;
}

export interface Dataset extends DatasetBase {
  // Extended properties if any
}

// New: Package structure for Import/Export
export interface ExportPackage {
  version: string;
  dashboard: Dashboard;
  dataSources: DataSource[];
  datasets: Dataset[];
  exportedAt: number;
}
